{
  "openapi": "3.0.0",
  "info": {
    "title": "Projeto de Animais Perdidos ou Doados",
    "description": "API para busca de animais perdidos e adoção de animais disponíveis.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/"
    }
  ],
  "tags": [
    {
      "name": "Usuários"
    },
    {
      "name": "Animais Perdidos"
    },
    {
      "name": "Animais para Adoção"
    }
  ],
  "paths": {
    "/users/registered": {
      "post": {
        "tags": [
          "Usuários"
        ],
        "summary": "Cadastrar novo usuário",
        "description": "Rota para cadastrar um novo usuário.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserRegistered"
              },
              "examples": {
                "Exemple Json": {
                  "value": {
                    "name": "Nome do usuário",
                    "email": "email@example.com",
                    "cpf": "12345678900",
                    "phone": "123456789",
                    "password": "senha123",
                    "address": {
                      "cep": "25264253",
                      "complement": "502"
                    }
                  }
                },
                "Exemple Type": {
                  "value": {
                    "name": "string",
                    "email": "string",
                    "cpf": "string",
                    "phone": "string",
                    "password": "string",
                    "address": {
                      "cep": "string",
                      "complement": "string"
                    }
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Usuário cadastrado com sucesso!"
          },
          "400": {
            "description": "Erro ao cadastrar usuário!"
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "Usuários"
        ],
        "summary": "Login usuário",
        "description": "Rota login do usuário.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserLogin"
              },
              "examples": {
                "Example Json": {
                  "value": {
                    "email": "email@example.com",
                    "password": "123456"
                  }
                },
                "Example Type": {
                  "value": {
                    "email": "string",
                    "password": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Usuário cadastrado com sucesso!"
          },
          "400": {
            "description": "Erro ao cadastrar usuário!"
          }
        }
      }
    },
    "/users/{userId}": {
      "put": {
        "tags": [
          "Usuários"
        ],
        "summary": "Editar dados do usuário",
        "description": "Rota para editar dados do usuário.",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "description": "ID do usuário",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "integer",
              "format": "int64",
              "example": 123
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserEdited"
              },
              "examples": {
                "Example Json": {
                  "value": {
                    "name": "Nome do usuário",
                    "email": "email@example.com",
                    "cpf": "12345678900",
                    "phone": "123456789",
                    "password": "senha123",
                    "address": {
                      "cep": "25264253",
                      "complement": "502"
                    }
                  }
                },
                "Exemple Type": {
                  "value": {
                    "name": "string",
                    "email": "string",
                    "cpf": "string",
                    "phone": "string",
                    "password": "string",
                    "address": {
                      "cep": "string",
                      "complement": "string"
                    }
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Usuário cadastrado com sucesso!"
          },
          "400": {
            "description": "Erro interno!"
          }
        }
      }
    },
    "/animals-found/registered": {
      "post": {
        "tags": [
          "Animais Encontrados"
        ],
        "summary": "Cadastrar novo animal encontrado",
        "description": "Rota para cadastrar um novo animal encontrado.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AnimalsFound"
              },
              "examples": {
                "Example Json": {
                  "value": {
                    "photo": "Caminho para a foto do animal",
                    "local_encontrado": "Descrição ou endereço do local encontrado",
                    "species": "Espécie do animal",
                    "race": "Raça do animal",
                    "age": "Filhote || adulto || idoso",
                    "color": "Cor do animal",
                    "size": "Tamanho do animal",
                    "distinctive_characteristics": "Características distintivas do animal",
                    "user_id": "usuario id"
                  }
                },
                "Example Type": {
                  "value": {
                    "photo": "string",
                    "local_encontrado": "string",
                    "species": "string",
                    "race": "string",
                    "age": "string",
                    "color": "string",
                    "size": "string",
                    "distinctive_characteristics": "string",
                    "user_id": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Animal cadastrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AnimalsFound"
                },
                "examples": {
                  "Example Json": {
                    "value": {
                      "id": 1,
                      "foto": "Caminho para a foto do animal",
                      "local_encontrado": "Descrição ou endereço do local encontrado",
                      "species": "Espécie do animal",
                      "race": "Raça do animal",
                      "age": "Filhote || adulto || idoso",
                      "color": "Cor do animal",
                      "size": "Tamanho do animal",
                      "distinctive_characteristics": "Características distintivas do animal",
                      "user_id": "usuario id"
                    }
                  },
                  "Example Type": {
                    "value": {
                      "photo": "string",
                      "local_encontrado": "string",
                      "species": "string",
                      "race": "string",
                      "age": "string",
                      "color": "string",
                      "size": "string",
                      "distinctive_characteristics": "string",
                      "user_id": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Erro ao cadastrar animal"
          }
        }
      }
    },
    "/lost-animals/registered": {
      "post": {
        "tags": [
          "Animais Perdidos"
        ],
        "summary": "Cadastrar novo animal perdido",
        "description": "Rota para cadastrar um novo animal perdido.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LostAnimals"
              },
              "examples": {
                "Example Json": {
                  "value": {
                    "species": "Espécie do animal",
                    "race": "Raça do animal",
                    "age": "Filhote || adulto || idoso",
                    "color": "Cor do animal",
                    "size": "Tamanho do animal",
                    "distinctive_characteristics": "Características distintivas do animal",
                    "date_loss": "Data da perda",
                    "location_loss": "Local onde o animal foi perdido",
                    "user_id": "usuario id"
                  }
                },
                "Example Type": {
                  "value": {
                    "photo": "string",
                    "local_encontrado": "string",
                    "species": "string",
                    "race": "string",
                    "age": "string",
                    "color": "string",
                    "size": "string",
                    "distinctive_characteristics": "string",
                    "user_id": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Animal perdido cadastrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LostAnimals"
                },
                "examples": {
                  "Example Json": {
                    "value": {
                      "id": 1,
                      "species": "Espécie do animal",
                      "race": "Raça do animal",
                      "age": "Filhote || adulto || idoso",
                      "color": "Cor do animal",
                      "size": "Tamanho do animal",
                      "distinctive_characteristics": "Características distintivas do animal",
                      "date_loss": "Data da perda",
                      "location_loss": "Local onde o animal foi perdido",
                      "user_id": "usuario id"
                    }
                  },
                  "Example Type": {
                    "value": {
                      "photo": "string",
                      "local_encontrado": "string",
                      "species": "string",
                      "race": "string",
                      "age": "string",
                      "color": "string",
                      "size": "string",
                      "distinctive_characteristics": "string",
                      "user_id": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Erro ao cadastrar animal perdido"
          }
        }
      }
    },
    "/animals-adoption/registered": {
      "post": {
        "tags": [
          "Animais para Adoção"
        ],
        "summary": "Cadastrar novo animal para adoção",
        "description": "Rota para cadastrar um novo animal disponível para adoção.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AvailableAnimals"
              },
              "examples": {
                "Example Json": {
                  "value": {
                    "species": "Espécie do animal",
                    "race": "Raça do animal",
                    "age": "Filhote || adulto || idoso",
                    "color": "Cor do animal",
                    "size": "Tamanho do animal",
                    "distinctive_characteristics": "Características distintivas do animal",
                    "informacoes_personalidade": "Informações sobre a personalidade do animal",
                    "user_id": "id usuario"
                  }
                },
                "Example Type": {
                  "value": {
                    "photo": "string",
                    "local_encontrado": "string",
                    "species": "string",
                    "race": "string",
                    "age": "string",
                    "color": "string",
                    "size": "string",
                    "distinctive_characteristics": "string",
                    "user_id": "string"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Animal para adoção cadastrado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AvailableAnimals"
                },
                "examples": {
                  "Example Json": {
                    "value": {
                      "id": 1,
                      "species": "Espécie do animal",
                      "race": "Raça do animal",
                      "age": "Filhote",
                      "color": "Cor do animal",
                      "size": "Tamanho do animal",
                      "distinctive_characteristics": "Características distintivas do animal",
                      "informacoes_personalidade": "Informações sobre a personalidade do animal",
                      "user_id": "id usuario"
                    }
                  },
                  "Example Type": {
                    "value": {
                      "photo": "string",
                      "local_encontrado": "string",
                      "species": "string",
                      "race": "string",
                      "age": "string",
                      "color": "string",
                      "size": "string",
                      "distinctive_characteristics": "string",
                      "user_id": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Erro ao cadastrar animal para adoção"
          }
        }
      }
    },
    "/available-animal/find": {
      "get": {
        "tags": [
          "Animais para Adoção"
        ],
        "summary": "Buscar animais para adoção",
        "description": "Rota para buscar animais disponíveis para adoção.",
        "parameters": [
          {
            "name": "especie",
            "in": "query",
            "description": "Espécie do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "raca",
            "in": "query",
            "description": "Raça do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "cor",
            "in": "query",
            "description": "Cor do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tamanho",
            "in": "query",
            "description": "Tamanho do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "caracteristicas_distintivas",
            "in": "query",
            "description": "Características distintivas do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de animais para adoção encontrada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/AvailableAnimalsFind"
                  }
                },
                "examples": {
                  "Example Json": {
                    "value": [
                      {
                        "id": 1,
                        "species": "Espécie do animal",
                        "race": "Raça do animal",
                        "age": "Filhote",
                        "color": "Cor do animal",
                        "size": "Tamanho do animal",
                        "distinctive_characteristics": "Características distintivas do animal",
                        "informacoes_personalidade": "Informações sobre a personalidade do animal",
                        "user_id": "id usuario"
                      },
                      {
                        "id": 2,
                        "species": "Espécie do animal",
                        "race": "Raça do animal",
                        "age": "Filhote || adulto || idoso",
                        "color": "Cor do animal",
                        "size": "Tamanho do animal",
                        "distinctive_characteristics": "Características distintivas do animal",
                        "informacoes_personalidade": "Informações sobre a personalidade do animal",
                        "user_id": "id usuario"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Erro ao buscar animais para adoção"
          }
        }
      }
    },
    "/lost-animal/find": {
      "get": {
        "tags": [
          "Animais Perdidos"
        ],
        "summary": "Buscar animais perdidos",
        "description": "Rota para buscar animais perdidos",
        "parameters": [
          {
            "name": "especie",
            "in": "query",
            "description": "Espécie do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "raca",
            "in": "query",
            "description": "Raça do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "cor",
            "in": "query",
            "description": "Cor do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tamanho",
            "in": "query",
            "description": "Tamanho do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "caracteristicas_distintivas",
            "in": "query",
            "description": "Características distintivas do animal",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de animais para adoção encontrada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/LostAnimalsFind"
                  }
                },
                "examples": {
                  "Example Json": {
                    "value": [
                      {
                        "id": 1,
                        "species": "Espécie do animal",
                        "race": "Raça do animal",
                        "age": "Filhote",
                        "color": "Cor do animal",
                        "size": "Tamanho do animal",
                        "distinctive_characteristics": "Características distintivas do animal",
                        "informacoes_personalidade": "Informações sobre a personalidade do animal",
                        "user_id": "id usuario"
                      },
                      {
                        "id": 2,
                        "species": "Espécie do animal",
                        "race": "Raça do animal",
                        "age": "Filhote || adulto || idoso",
                        "color": "Cor do animal",
                        "size": "Tamanho do animal",
                        "distinctive_characteristics": "Características distintivas do animal",
                        "informacoes_personalidade": "Informações sobre a personalidade do animal",
                        "user_id": "id usuario"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Erro ao buscar animais perdido"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserRegistered": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "address": {
            "$ref": "#/components/schemas/UserRegistered_address"
          }
        }
      },
      "UserLogin": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "UserEdited": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "address": {
            "$ref": "#/components/schemas/UserRegistered_address"
          }
        }
      },
      "AnimalsFound": {
        "type": "object",
        "properties": {
          "photo": {
            "type": "string"
          },
          "local_encontrado": {
            "type": "string"
          },
          "species": {
            "type": "string"
          },
          "race": {
            "type": "string"
          },
          "age": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "distinctive_characteristics": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        }
      },
      "LostAnimals": {
        "type": "object",
        "properties": {
          "species": {
            "type": "string"
          },
          "race": {
            "type": "string"
          },
          "age": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "distinctive_characteristics": {
            "type": "string"
          },
          "date_loss": {
            "type": "string"
          },
          "location_loss": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        }
      },
      "AvailableAnimals": {
        "type": "object",
        "properties": {
          "species": {
            "type": "string"
          },
          "race": {
            "type": "string"
          },
          "age": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "distinctive_characteristics": {
            "type": "string"
          },
          "informacoes_personalidade": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        }
      },
      "LostAnimalsFind": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "species": {
            "type": "string"
          },
          "race": {
            "type": "string"
          },
          "age": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "distinctive_characteristics": {
            "type": "string"
          },
          "informacoes_personalidade": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        }
      },
      "AvailableAnimalsFind": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "species": {
            "type": "string"
          },
          "race": {
            "type": "string"
          },
          "age": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "size": {
            "type": "string"
          },
          "distinctive_characteristics": {
            "type": "string"
          },
          "informacoes_personalidade": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        }
      },
      "UserRegistered_address": {
        "type": "object",
        "properties": {
          "cep": {
            "type": "string"
          },
          "complement": {
            "type": "string"
          }
        }
      }
    }
  }
}